language: node_js
notifications:
  email: true
node_js:
  - 'node'
  - '10'
after_success:
  - npm run build
  - npx travis-deploy-once "npm run semantic-release"
  - npm run test:coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
sudo: false
